### ISSUE TITLE
Eth is not drained even once

### ISSUE THREAD

**Issue by joy4sure** [Dsummers91/HackThisContract#3]
Hey, sorry to disturb you, but I stuck in this problem for days. I cannot really run your solution here. I can compile it under the compiler of 0.4.11. However the program never go into the fallback function. 
I deployed the attacker at 0xbe1edeb8d43af17de73646a7f75e837fe724a505
the testToken at 0xd9afc24362a208afb4d99bffaf32e72d444fd315
By the way, the deposit function also not working, so I changed it to 
`token.deposit.value(msg.value)();`

**Comment by joy4sure** [comment]
Ok, got it now. Really understand what is enough gas.

**Comment by Dsummers91** [comment]
Sorry just now seeing that, glad you got it worked out
